name: merge-squash-main
on:
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: merge-to-main
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git clone https://github.com/moieo/PChat.git PChat
          cd PChat
          git fetch origin
          git checkout main
          git merge dev
          git push --force "https://github-actions[bot]:${{ secrets.GITHUB_TOKEN }}@github.com/moieo/PChat.git" main:main
